services:
  pack218_db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: pack218
    volumes:
      - pack218_db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  pack218_webapp:
    # container_name: pack218_webapp
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pack218
    ports:
      - "8001:8001"
    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#networks:
#  db:
#    driver: bridge
volumes:
  pack218_db: