"""V1

Revision ID: 247b1f7cd24b
Revises: 
Create Date: 2025-02-13 08:07:25.462670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# https://arunanshub.hashnode.dev/using-sqlmodel-with-alembic
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '247b1f7cd24b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
