"""add capacity to event

Revision ID: efdb27d61ada
Revises: 247b1f7cd24b
Create Date: 2026-02-08 22:07:36.931794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# https://arunanshub.hashnode.dev/using-sqlmodel-with-alembic
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'efdb27d61ada'
down_revision: Union[str, None] = '247b1f7cd24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
