"""Init

Revision ID: fc29918ccfc4
Revises: 
Create Date: 2025-02-03 16:14:52.806484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# https://arunanshub.hashnode.dev/using-sqlmodel-with-alembic
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fc29918ccfc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
